In [2]:
import numpy as np

In [4]:
x=np.zeros((3, 4), dtype=int)

In [5]:
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
x=np.ones((2,3,4), dtype=np.int16)

In [8]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
x=np.arange(10,25,5)

In [13]:
x

array([10, 15, 20])

In [14]:
x=np.linspace(0,2,9)

In [15]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
x=np.full((2,2),7)

In [19]:
x

array([[7, 7],
       [7, 7]])

In [20]:
x=np.eye(2,2)

In [21]:
x

array([[1., 0.],
       [0., 1.]])

In [23]:
x=np.random.random((2,2))

In [24]:
x

array([[0.51694971, 0.28824725],
       [0.2155279 , 0.19515382]])

In [49]:
a=np.array([1,2,3,4])

In [27]:
b=np.array([5,6,7,8])

In [56]:
c=a-b

In [57]:
print(c)

[-4 -4 -4 -4]


In [55]:
d=a+b

In [32]:
print (d)

[ 6  8 10 12]


In [35]:
e=a*b

In [37]:
print(e)

[ 5 12 21 32]


In [38]:
f=a/b

In [39]:
print(f)

[0.2        0.33333333 0.42857143 0.5       ]


In [40]:
g=a>b

In [41]:
print(g)

[False False False False]


In [42]:
h=a==b

In [43]:
print(h)

[False False False False]


In [44]:
j=a<b

In [45]:
print(j)

[ True  True  True  True]


In [58]:
a.size

4

In [59]:
b.size

4

In [61]:
np.exp(b)

array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704])

In [62]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [64]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [65]:
np.sqrt(b)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])